# Generated by Django 4.0.6 on 2022-08-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0003_kakaowebtoondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='items'),
        ),
    ]
